worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        # Escuchamos en el 8080 interno (por seguridad de contenedores sin privilegios)
        listen 8080;
        server_name localhost;

        # 1. El bloque vital para React (La Interfaz Web)
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            # Esto evita el 404 al recargar la página en React
            try_files $uri $uri/ /index.html;
        }

        # 2. Proxy Inverso: Interceptar llamadas a Ventas
        location /api/v1/ventas {
            proxy_pass http://APP_PRIVATE_IP:8080/api/v1/ventas;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Proxy Inverso: Interceptar llamadas a Despachos
        location /api/v1/despachos {
            proxy_pass http://APP_PRIVATE_IP:8081/api/v1/despachos;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}